### PR TITLE
Add request interceptor to feign configuration

### PR DESCRIPTION
**Pull request by sebastian-sch**
Add the possibility to use ```requestInterceptor``` with ```Feign```

see https://github.com/spring-cloud/spring-cloud-netflix/issues/159

### CODE REVIEW

**Comment by spencergibb** [comment]
Should you allow for more than one `RequestIntercepter`?

**Comment by sebastian-sch** [comment]
I think both should be possible. Now you can add a collection of ```RequestIntercepter``` or a single a ```RequestIntercepter``` or both a collection and additional a single ```RequestIntercepter``` (not sure if this is required, but now you have the most flexibility)

**Comment by sebastian-sch** [comment]
@spencergibb Is the change OK? Would it be possible to merge it or are there additional development required?

**Comment by spencergibb** [comment]
@sebastian-sch I don't think it makes sense to have both `requestInterceptor` and `requestInterceptors` since spring will wire both up all of the time.  If you have one `requestInterceptor`, spring will wire both.

**Comment by spencergibb** [comment]
Closed in favor of d78982973ece5463fea216a42e247aa20f3fbea4

Thanks for the PR.  I basically did just the `List<RequestInterceptor>` and added some tests.

Keep `em coming.

**Comment by sebastian-sch** [comment]
Sorry I hadn't time to change the PR. Thanks for the fix, works well.

**Pull request closed without merging**
