### PR TITLE
Fallback provider 

### PR DESCRIPTION
**Pull request by DominikMostek**
This is a followup for PR #2255.  Deprecated interface is removed and documentation updated.

### CODE REVIEW

**Comment by spencergibb** [comment]
We'll need a note in the release notes

**Comment by ryanjbaxter** [comment]
@spencergibb I think we can hold off on merging this until we get the 2.0.x branch building again

**Comment by spencergibb** [comment]
This PR needs to be rebased with all of the changes in the meantime.

**Comment by DominikMostek** [comment]
Hi @spencergibb I have rebased the changes on `2.0.x` branch, However still cant build the branch.

**Comment by ryanjbaxter** [comment]
@DominikMostek not even locally?

**Comment by DominikMostek** [comment]
@ryanjbaxter Now it passes when running with `mvnw`, but still not able to run in idea and run the tests.

**Comment by ryanjbaxter** [comment]
Can you rebase again?  I just pushed some fixes for some tests in the 2.0.x branch.

Also its best now to run the build by running `build.sh` in the `scripts` folder.  This will build the contract test jar first and then run the netflix build.

**Pull request closed without merging**
