### PR TITLE
#1057 add property zuul.sslHostnameValidationEnabled to be able to di…

### PR DESCRIPTION
**Pull request by pcornelissen**
…sable the hostname validation in the simpleHostRoutingFilter

As announced in the gitter chat. I have signed the CLA.

### CODE REVIEW

**Comment by spencergibb** [comment]
@pcornelissen I'm unable to access your fork.

**Comment by pcornelissen** [comment]
Hmm, weird, it is a public repo :-/
I have given your user write access, please try again.

**Comment by spencergibb** [comment]
I see. My little JS helper uses `https://github.com/pcornelissen/spring-cloud-netflix.git` not `https://github.com/orchit/spring-cloud-netflix`. Sorry about the noise.

**Comment by spencergibb** [comment]
Closed with some polish via 5e9c71e0e3c5b1892cc04fa39af06131add619af

**Pull request closed without merging**
