### PR TITLE
Build query string from context instead of original request

### PR DESCRIPTION
**Pull request by qbast**
Recreate query string from either getCurrentContext().getRequestQueryParams()
or original request as fallback. This allows to override query string
params in pre filters and matches behaviour of RibbonRoutingFilter

gh-426

### CODE REVIEW

**Comment by spencergibb** [comment]
Two questions, how about a unit test to verify your fix?  Also, have you signed the [contributor agreement](https://support.springsource.com/spring_committer_signup)?

**Comment by qbast** [comment]
1) I am unsure how to go about it - SimpleHostRoutingFilter is quite opaque and I don't see a way to mock HttpClient, override forwardRequest() or intercept constructed request in another way.
2) Yes.

**Comment by spencergibb** [comment]
Don't mock make a real request ala https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/zuul/SampleZuulProxyApplicationTests.java

**Comment by qbast** [comment]
I added two tests - one showing that overriding query string works and another to verify that it does not break normal case.

**Comment by spencergibb** [comment]
@qbast very nice, thanks!

**Comment by spencergibb** [comment]
Merged via 22ed8818053d3915200e422c6d56801af8a861d6

**Comment by Xero314** [comment]
I know this is a closed issue, but I wanted to bring to everyone's attention that this implementation is going to be problematic because URLEncoder does not properly encode query parameters as it encodes "/" and "?" which are not necessary to be encoded in query parameter values and will cause some applications to fail as they do not expected an encoded value here.

**Comment by spencergibb** [comment]
@Xero314 you're right it is closed. Please open a new issue if you think there is an issue.

**Pull request closed without merging**
