### PR TITLE
Move eureka-client specific code to separate module.

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-579

Rather than move ribbon, feign, zuul etc.. out of core I decided to move eureka-client out.

### CODE REVIEW

**Comment by spencergibb** [comment]
Currently compiles, haven't run tests yet.

**Comment by spencergibb** [comment]
I think I'm done with this. The brewery tests pass on my local machine. Not sure why things hang on integration tests.

@dsyer @adriancole @marcingrzejszczak

**Comment by adriancole** [comment]
there are errors in the console output like this. Are they unrelated? Still curious how to see what's hung that results in 10m of no-output. Maybe there's a travis tool or methodology to capture details when a container is killed?

```
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/cloud/netflix/test/NoopDiscoveryClientConfiguration.class] cannot be opened because it does not exist
```

**Comment by adriancole** [comment]
We can also try commenting out the trusty beta container travis config. no reason to suspect it is involved, but little effort to try.

**Comment by marcingrzejszczak** [comment]
I've sent an email to Travis support with regards to this case - I'll ping you once I get some answer.

**Comment by marcingrzejszczak** [comment]
Actually - https://travis-ci.org/spring-cloud/spring-cloud-netflix the build has gone through but it just failed

**Pull request merged**
