### PR TITLE
disables httpclient auto decompression of encoded data

### PR DESCRIPTION
**Pull request by tranhungt**
https://github.com/spring-cloud/spring-cloud-netflix/issues/1480

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@tranhungt Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1591)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1591) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@tranhungt Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1591)!

**Comment by tranhungt** [comment]
It's actually disabling decompression if compression exists. Nothing happens if the content isn't compressed. I can add more tests to show the other cases.

**Comment by spencergibb** [comment]
@tranhungt can you rebase?

**Comment by tranhungt** [comment]
@spencergibb Yep, just did.

**Comment by spencergibb** [comment]
Rebased and merged with a little polish via 22248dd9e9bb88faed280988f3cde33f2c3a7667

**Pull request closed without merging**
