### PR TITLE
Replaced incorrect @PathParameter with @PathVariable

### PR DESCRIPTION
**Pull request by geoand**

### CODE REVIEW

**Comment by spencergibb** [comment]
@geoand have you signed the [contributors agreement](https://support.springsource.com/spring_committer_signup)?

**Comment by geoand** [comment]
@spencergibb Yes I have. I can give you the 19-digit confirmation number if you need it.

**Comment by spencergibb** [comment]
@geoand nope, thanks!

**Comment by geoand** [comment]
@spencergibb You're welcome!

**Pull request merged**
