### PR TITLE
Allow the Hystrix `ExecutionIsolationStrategy` to be customized in zuul.

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-339

/cc @dsyer @brenuart

### CODE REVIEW

**Comment by stephlag** [comment]
This change was never merged into the master branch. Was this intended?

**Comment by spencergibb** [comment]
yeah, code diverged too much. the issue is still open.

**Comment by stephlag** [comment]
OK, as we have performance limitations using the semaphore approach, we would need this change.
I can report this change on the latest master if nobody else works on this issue.

**Comment by dsyer** [comment]
Why not leave a comment on the open issue then?

**Comment by stephlag** [comment]
Done

**Pull request closed without merging**
