### PR TITLE
Ribbon default client properties file

### PR DESCRIPTION
**Pull request by sabareeshkkanan**
Default ribbon properties can be now used by specifying ribbon. without specifying client name

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
As far as I know this is already possible, you can specify properties without the client name.

**Comment by spencergibb** [comment]
You can, but not for the beans created. I added that feature

**Comment by sabareeshkkanan** [comment]
> As far as I know this is already possible, you can specify properties without the client name.

This is not really happening when tested for this feature

**Comment by spencergibb** [comment]
ribbon is no longer supported

**Pull request closed without merging**
