### PR TITLE
adds caution about property name case-sensitivity

### PR DESCRIPTION
**Pull request by sshaghafi**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@sshaghafi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3533)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3533) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@sshaghafi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3533)!

**Comment by OlgaMaciaszek** [comment]
Hi, @sshaghafi thanks for this contribution. Makes sense. Please add a comma in between of:  "project they"

**Comment by sshaghafi** [comment]
> Hi, @sshaghafi thanks for this contribution. Makes sense. Please add a comma in between of: "project they"

Thanks, @OlgaMaciaszek, for your suggestion. I've updated the PR.

**Pull request merged**
