### PR TITLE
Always forward Content-Length header from origin when set 

### PR DESCRIPTION
**Pull request by brenuart**
unless response is compressed and client does not support it.

Fix for #2832

### CODE REVIEW

**Comment by brenuart** [comment]
Sorry - but I have no idea why the test failed :-(
I don't see how it is related to the changes I have made...

**Comment by spencergibb** [comment]
rebuilding

**Comment by spencergibb** [comment]
looks better

**Comment by ryanjbaxter** [comment]
Any way to add a test for this?

**Comment by brenuart** [comment]
Working on it.

 

Unfortunately, it appears the existing `SendResponseFilterTests` are possibly making incorrect assumptions about the actual behaviour of Zuul filters.

For instance, I’m worried about the following line of code: https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-zuul/src/test/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilterTests.java#L203

 

If Zuul would behave this way, a Content-length header would always be included in all responses – which is not the case.

Moreover, I cannot find anywhere in the existing filters any traces of setting this property on the RequestContext.

**Pull request merged**
