### PR TITLE
Update zuul-core to 1.3.1 version

### PR DESCRIPTION
**Pull request by Aloren**

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@Aloren have you taken a look at the test failures?  They seem like they might be related.

**Comment by spencergibb** [comment]
It's an ordering problem. That test doesn't fail in isolation.

**Comment by spencergibb** [comment]
The tests still need to be fixed, because I replicated it locally.

**Comment by spencergibb** [comment]
Next email :-) #2565

**Comment by ryanjbaxter** [comment]
I reverted the commit.  With M6 looming I would rather wait on this.

@Aloren if you could look at the failing tests and submit it again that would be great.

**Comment by Aloren** [comment]
I ran tests on my local machine and they are green, so I thought that they were not stable from the beginning. I will look into it and try to fix.

**Comment by ryanjbaxter** [comment]
They failed on my machine and on our Jenkins build as well  https://jenkins.spring.io/job/spring-cloud-netflix-master-ci/4650/

**Pull request merged**
