### PR TITLE
add config option to not ignore security headers (#1096)

### PR DESCRIPTION
**Pull request by mduesterhoeft**
Addresses #1096

### CODE REVIEW

**Comment by mduesterhoeft** [comment]
@spencergibb added the test - anything else to take care of

**Comment by mduesterhoeft** [comment]
@spencergibb sounds reasonable to document such an option - should it go here? Below the section on sensitive headers? https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc#cookies-and-sensitive-headers

**Comment by spencergibb** [comment]
@mduesterhoeft yes, I should live next to the existing sensitive headers docs.

**Comment by mduesterhoeft** [comment]
@spencergibb added the docs you mentioned - what do you think?

**Pull request merged**
