### PR TITLE
change HttpServletResponse to HttpServletRequest

### PR DESCRIPTION
**Pull request by spccold**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@spccold Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1907)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1907) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@spccold Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1907)!

**Comment by spccold** [comment]
@spencergibb please hava a look!

**Comment by ryanjbaxter** [comment]
Is there an issue associated with this PR?  If so can you add it to the description?

**Comment by spccold** [comment]
@ryanjbaxter  no issue associated with this PR

`RibbonRoutingFilter.java`
~~~java
private boolean useServlet31 = true;

public RibbonRoutingFilter(ProxyRequestHelper helper,
						   RibbonCommandFactory<?> ribbonCommandFactory,
						   List<RibbonRequestCustomizer> requestCustomizers) {
	this.helper = helper;
	this.ribbonCommandFactory = ribbonCommandFactory;
	this.requestCustomizers = requestCustomizers;
	// To support Servlet API 3.0.1 we need to check if getcontentLengthLong exists
	try {
		HttpServletResponse.class.getMethod("getContentLengthLong");
	} catch(NoSuchMethodException e) {
		useServlet31 = false;
	}
}
......
long contentLength = useServlet31 ? request.getContentLengthLong(): request.getContentLength();
~~~
`getContentLengthLong` method in HttpServletRequest rather than HttpServletResponse

**Comment by ryanjbaxter** [comment]
OK I see.  In the future open an issue or at least provide a description of what you are fixing in the PR.  Thanks!

**Comment by spccold** [comment]
@ryanjbaxter Ok, thanks

**Pull request merged**
