### PR TITLE
Corrected example of providing Turbine cluster name via instance metadata map

### PR DESCRIPTION
**Pull request by kaczynskid**
* Corrected documentation
 * Added test to prove correctness

### CODE REVIEW

**Comment by spencergibb** [comment]
@kaczynskid have you signed the [Contributor agreement](https://support.springsource.com/spring_committer_signup)?  Sorry if you've been asked before.

**Comment by kaczynskid** [comment]
No, I have not, and was not asked yet. I should select Spring Cloud as
project? And whom should I put as project lead in the form?

**Comment by spencergibb** [comment]
No problem, it is [in the docs](https://github.com/spring-cloud/spring-cloud-netflix#sign-the-contributor-license-agreement).  Project is Spring Cloud and myself (Spencer Gibb) or Dave Syer as lead.

**Comment by kaczynskid** [comment]
OK, done. My  confirmation number is *127620150623070409*.

**Pull request merged**
