### PR TITLE
Simplify some code  in Eureka with java 8 features

### PR DESCRIPTION
**Pull request by OLPMO**

### CODE REVIEW

**Comment by OlgaMaciaszek** [comment]
Hi, @OLPMO This looks good but could be added to Greenwich release train as well. Can you submit this against the `2.1.x` branch?

**Comment by OLPMO** [comment]
Do you mean i could synchronize these changes in 2.1.x branch? @OlgaMaciaszek

**Comment by OLPMO** [comment]
@OlgaMaciaszek I have synced my changes to the branch 2.1.x .If I misunderstood what you mean,please tell me immediately, I would revert this commit.

**Comment by OlgaMaciaszek** [comment]
Sorry for not getting back to you earlier @OLPMO What I mean is instead of doing this PR against the master branch do the PR to merge your branch to `2.1.x`, like this these changes will get included in Greenwich release train as well. We merge 2.1.x to master each time anyway.

**Comment by OLPMO** [comment]
It doesn't matter. @OlgaMaciaszek

**Comment by OlgaMaciaszek** [comment]
@OLPMO  It was a good PR, it should just be added to Greenwich release train instead. It's very simple to resubmit the PR against a different branch if there are no conflicts.

**Pull request closed without merging**
