### PR TITLE
some codes style optimization

### PR DESCRIPTION
**Pull request by lidengke**
just some codes style optimization

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@lidengke Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3966)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3966) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@lidengke Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3966)!

**Comment by spencergibb** [comment]
this failed checkstyle. can you update it?

**Comment by spencergibb** [comment]
We're cleaning out the issue tracker and closing issues that we've not seen much demand to fix. Feel free to comment with additional justifications if you feel that this one should not have been closed.

**Pull request closed without merging**
