### PR TITLE
Update ZuulHandlerMapping to use PathMatcher

### PR DESCRIPTION
**Pull request by salavessa**
Zuul ignored patterns have inconsistent behaviour on edge cases

fixes gh-1575

### CODE REVIEW

**Comment by salavessa** [comment]
Sorry, can't see any logical test fitting in for this fix.
The problem is that values from the same object (`ZuulProperties.ignoredPatterns`) and whithin the same flow are being checked against two different implementations (probably inadvertently) which are clearly not 100% compatible (`PatternMatchUtils.simpleMatch` vs `AntPathMatcher.match`) as one is pure wildcard and the other has embedded path logic.
If you are looking for some cases where the used implementations fail to match, please check below:
```
PATTERN '/*'
	'/p1/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1*'
	'/p1/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*'
	'/p1/p2/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**'
	'/p1' AntPathMatcher=true; MatchUtils=false
PATTERN '/p*'
	'/p1/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p3*'
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p3**'
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p3/*'
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p3/**'
	'/p1/p2/p3' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/**/p3'
	'/p1/p2/p3/' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/**/p3*'
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**/p3**'
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**/p3/'
	'/p1/p2/p3' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/**/p3/*'
	'/p1/p2/p3/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**/p3/**'
	'/p1/p2/p3' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/*/p4'
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p4*'
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p4**'
	'/p1/p2/p3/p4' AntPathMatcher=false; MatchUtils=true
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p4/'
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p4/*'
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/*/p4/**'
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**/p4'
	'/p1/p2/p3/p4/' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/**/p4/'
	'/p1/p2/p3/p4' AntPathMatcher=true; MatchUtils=false
PATTERN '/p1/**/p4/*'
	'/p1/p2/p3/p4/' AntPathMatcher=false; MatchUtils=true
PATTERN '/p1/**/p4/**'
	'/p1/p2/p3/p4' AntPathMatcher=true; MatchUtils=false
```
Thanks

**Comment by spencergibb** [comment]
rebuilding

**Comment by spencergibb** [comment]
I'm hesitant to make a change like this without a test. If you can't come up with one, I'll take a look later.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module.

**Pull request closed without merging**
