### PR TITLE
Issue-3305. Way to set securePortEnabled option for sidecar

### LINKED ISSUE #3305: [Sidecar] Eureka set secure port
I have python application with ssl on custom port (5000), and cannot set secure port in eureka instance config bean. Can you add possible configure if this port is nonSecure or secure ?? I add screen with place when configure port in eureka instance config bean

image

### PR DESCRIPTION
**Pull request by dev-priporov**
Fixes #3305 
Added a way to set _securePortEnabled_ flag by _sidecar.secure-port-enabled_ option.
Test is added.

Seems like I have some trouble with Eclipse-formatter-plugin, because it changed existing format files.

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
We also need documentation for the new property

**Comment by ryanjbaxter** [comment]
I mean documentation in https://github.com/spring-cloud/spring-cloud-netflix/blob/master/docs/src/main/asciidoc/spring-cloud-netflix.adoc

**Comment by dev-priporov** [comment]
The doc is updated, added short description for the `sidecar.secure-port-enabled`

**Comment by dev-priporov** [comment]
@spencergibb sure, it's done

**Pull request merged**
