### PR TITLE
Fixes gh-1308 on master

### PR DESCRIPTION
**Pull request by garciafl**
Deleting the "RibbonCommand" suffix on master

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@garciafl Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1310)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1310) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@garciafl Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1310)!

**Comment by ryanjbaxter** [comment]
@garciafl thanks for the pull request!  Can you look at the test failures?  Also I believe @spencergibb said this should be fixed on the 1.1.x branch (I could be wrong though)

**Comment by ryanjbaxter** [comment]
Oh i see the other pull request for the 1.1.x branch now :)

**Comment by spencergibb** [comment]
Closed via 048d401309287928f6843a10626fe20aeada6645

**Pull request closed without merging**
