### PR TITLE
Add Default Client TimeOut.

### PR DESCRIPTION
**Pull request by wzwllu**
Add connectRequestTimeout，connectTimeout，readTimeout。

### CODE REVIEW

**Comment by wzwllu** [comment]
Why the tests failed on CircleCI?
Only add the timeOut Config.

**Comment by wzwllu** [comment]
If remove codes , CL is error too;
It's  7d696c9....
please check the CL test.

**Comment by OlgaMaciaszek** [comment]
Hello, @wzwllu Thanks for submitting the PR. The tests will fail on `main` currently due to necessary changes waiting for merge in Netflix/Eureka. Please submit your PR against the `3.1.x` branch instead of `main`.

**Review by OlgaMaciaszek — COMMENTED** [review]
Please modify so that the values are configurable via `.properties` files, for example by adding a static class dedicated to Apache Client properties in `EurekaClientConfigBean`.  Also, make sure the default values are set up there.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Please modify so that the values are configurable via .properties files, for example by adding a static class dedicated to Apache Client properties in EurekaClientConfigBean. Also, make sure the default values are set up there.
Please add tests and documentation.
Also, as indicated in the previous comment, please submit these changes against the `3.1.x` branch instead of `main`.

**Comment by OlgaMaciaszek** [comment]
Fixes gh-4110.

**Comment by kworkbee** [comment]
I wrote a new PR that satisfies the conditions. [Ref](https://github.com/spring-cloud/spring-cloud-netflix/pull/4148)

**Comment by OlgaMaciaszek** [comment]
Thanks, @wzwllu. Will take a look.

**Comment by OlgaMaciaszek** [comment]
Closing in favour of https://github.com/spring-cloud/spring-cloud-netflix/pull/4148.

**Pull request closed without merging**
