### PR TITLE
Add test on FormBodyWrapperFilter to avoid regressions (#1171)

### PR DESCRIPTION
**Pull request by VanRoy**
Hi @spencergibb, this PR is related to #1171.

It adds one integration test on FormBodyWrapperFilter to avoid new regression on this functionnality

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@VanRoy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1351)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1351) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by spencergibb** [comment]
ping @VanRoy for signing CLA.

**Comment by VanRoy** [comment]
@spencergibb I signed CLA 2 years ago :)  I will check why it's not synchronized on GitHub.

**Comment by spencergibb** [comment]
:-) I figured. @rwinch could help.

**Comment by rwinch** [comment]
@VanRoy Thanks for your contribution and sorry for the troubles with the new tooling. Did you get a chance to read the [FAQ](https://cla.pivotal.io/faq)? It has information on why the tooling might be confused on if you have signed the CLA or not along with steps to fix it.

**Comment by pivotal-issuemaster** [comment]
@VanRoy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1351)!

**Comment by spencergibb** [comment]
@VanRoy thanks! It's a one time deal to sync old and new. I appreciate it.

**Comment by spencergibb** [comment]
Merged with a touch of polish via 758ff920fc71d9a2aaf41d1250d3cc5ddd46b870. Used [StreamUtils](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/util/StreamUtils.html) rather than apache commons.

**Comment by VanRoy** [comment]
@spencergibb You're welcome, it's a pleasure to contribute a little bit on this great project

**Pull request closed without merging**
