### PR TITLE
fix 'RibbonRequest' cannot to encode issues

### PR DESCRIPTION
**Pull request by Coramo**
Issues is in here https://github.com/spring-cloud/spring-cloud-netflix/issues/1194

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Coramo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1247)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1247) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by ryanjbaxter** [comment]
@Coramo can you merge in the latest changes from master so the CircleCI build will run?

**Comment by spencergibb** [comment]
You need to prove that this fixes the problem with a test.

**Comment by pivotal-issuemaster** [comment]
@Coramo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1247)!

**Comment by Coramo** [comment]
@ryanjbaxter Sorry .

I don't know why CI cannot run the tests to be passed, i don't change anything in tests.
But, I pull the master again, CI is work.

And @spencergibb 

I added a test in `FeignLoadBalancerTests` and that can be show you why i doing that.

Important is : 
  `new RequestTemplate().append("xxx").request()`
  different from the
  `Request.create()`

**Comment by spencergibb** [comment]
@adriancole Any concerns moving from `RequestTemplate.request` to `Request.create`?

**Comment by adriancole** [comment]
@spencergibb sgtm

in this code, requesttemplate is localized (ex newed up inside a method and never returned), so basically it was used as a convenience to create Request (for lack of a builder on Request). seems more than ok to create Request directly.

**Pull request merged**
