### PR TITLE
Relocate package PropertyPlaceholderAutoConfiguration

### PR DESCRIPTION
**Pull request by utsman**
Change package to the autoconfigure.context subpackage

### CODE REVIEW

**Comment by spencergibb** [comment]
I'm away from my computer, are you moving from deprecated to not? Thanks.

**Comment by utsman** [comment]
Yes, i'll try to do

**Comment by ryanjbaxter** [comment]
Wouldnt this break Boot 1.4.x compatibility?

**Comment by spencergibb** [comment]
Yeah, we want to keep 1.4 compatibility.

**Pull request closed without merging**
