### PR TITLE
Fixes gh-2503

### PR DESCRIPTION
**Pull request by qcastel**
Obvious fix

https://github.com/spring-cloud/spring-cloud-netflix/issues/2503

### CODE REVIEW

**Comment by qcastel** [comment]
@spencergibb Would like to, however your current tests framework doesn't provide a mocking around certificates, etc. 

The current tests around this option are very minimal:

```
	@Test
	public void validationOfSslHostnamesCanBeDisabledViaProperty() {
		addEnvironment(this.context, "zuul.sslHostnameValidationEnabled=false");
		setupContext();
		assertFalse("Hostname verification should be disabled via property",
				getFilter().isSslHostnameValidationEnabled());
	}
```

Also, It's the first time I fork and contribute in this repo. I haven't managed to get it compiled yet. Any guideline available for contributors for making the project compile with intellij?

**Comment by qcastel** [comment]
Please Note that hostname validation is therefore disable by default. And it's even worth as this option is not only disabling the hostname validation but also SSL (see #2505).
Therefore, this should be considered as a security issue, a severe one IMHO.

**Comment by qcastel** [comment]
If you are interested in reproducing this, I created a sample project https://github.com/qcastel/forgerockmtlswithzuul which was originally to investigate on testing mutual TLS with a zuul proxy in front of a micro-service.

**Comment by ryanjbaxter** [comment]
I dont think you need to do to that extent.  I think we just need to vaildate that the correct `SSLContext` is setup in the connection manager.  If you look in `SimpleHostRoutingFilterTests` there are some reflection utilities you might be able to use to introspect the connection manager.

**Comment by ryanjbaxter** [comment]
ping @qcastel

**Comment by ryanjbaxter** [comment]
@qcastel are you interested in updating this pr?

**Comment by qcastel** [comment]
@ryanjbaxter I have the feeling I won't find the time for it. I apologies for not being able to contribute as I would.
If someone wants to take over that issue, don't hesitate to take it.

**Pull request closed without merging**
