### PR TITLE
Add ignoredFilters properties functionality remove default filters.

### PR DESCRIPTION
**Pull request by ArekCzarnik**
Hi *,

current is not possible to disable default filters in zuul, the default filters imo are hardwired at initialization time. 

After the this pull request you have the possibility to add an ignore list to the properties, wich influence the initialization of the default filters and disable some of that. 

example:
```
zuul:
 ignoreFilters:
     - sendResponseFilter
 routes:
   users:
     path: /**
     url: http://localhost:8080
```
Thanks,
Arek

### CODE REVIEW

**Comment by spencergibb** [comment]
@ArekCzarnik I like the idea, but have some issues with the implementation.  Why create the filter bean just to ignore it?  I'd prefer something like this:

```
@Bean
@ConditionalOnProperty(name = "zuul.filter.formBodyWrapper.enabled", matchIfMissing = true)
public FormBodyWrapperFilter formBodyWrapperFilter() {
   return new FormBodyWrapperFilter();
}
```

That way you could set `zuul.filter.formBodyWrapper.enabled=false` and for each filter you don't want.

**Comment by ArekCzarnik** [comment]
thanks, your prefer way looks better... i will try refactor my stuff.

**Comment by ArekCzarnik** [comment]
@spencergibb change the code to all filters with ConditionalOnProperty, the test is getting simple. 

what i found is  in the netflix stuff : 
```
public abstract class ZuulFilter implements IZuulFilter, Comparable<ZuulFilter> {
 
 private final DynamicBooleanProperty filterDisabled = DynamicPropertyFactory.getInstance().getBooleanProperty(this.disablePropertyName(), false);

    public String disablePropertyName() {
        return "zuul." + this.getClass().getSimpleName() + "." + this.filterType() + ".disable";
    }

    public boolean isFilterDisabled() {
        return this.filterDisabled.get();
    }
```
they already deal with disabling a filter...this can be used to turn off or turn on filter in a running application?

**Comment by spencergibb** [comment]
@ArekCzarnik looks like it can, is that sufficient for your needs?

**Comment by ArekCzarnik** [comment]
yes i already use it in my application.

**Comment by ArekCzarnik** [comment]
@spencergibb: yes it is sufficient for my needs. We can drop the pull request, maybe it would be nice to add this into the documentation as an example for disable the filters. Thanks for your time...

---
zuul:
 SendResponseFilter:
   post:
     disable: true

**Pull request closed without merging**
