### PR TITLE
InputStream should always be closed after reading contents from upstreams

### PR DESCRIPTION
**Pull request by craig-rueda**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@craig-rueda Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2500)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2500) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@craig-rueda Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2500)!

**Comment by spencergibb** [comment]
Are you seeing problems? This will require a test of some kind, I think.

**Comment by craig-rueda** [comment]
Yep, had to shim it ourselves. I'll work on a test and update.

**Comment by spencergibb** [comment]
Can you target 1.4.x branch? That way we can get the fix in Edgware

**Pull request closed without merging**
