### PR TITLE
Allow custom feign clients when not using ribbon.

### PR DESCRIPTION
**Pull request by spencergibb**
/cc @dsyer @marcingrzejszczak @adriancole 

Wondering if the scope of this is ok for 1.1.x or should it go in 1.2.0?

fixes gh-1143

### CODE REVIEW

**Comment by adriancole** [comment]
only suggestion might be to make the types extracted package private, since as far as I can tell, they don't yet need to be public

**Comment by spencergibb** [comment]
And I made some public because the test is in another package :-( I should make a new one.

**Comment by adriancole** [comment]
or move the tests to the same package?

**Comment by dsyer** [comment]
It seems like a small thing, but since you decided it wasn't a bug, I would say lets put it in 1.2.0. We want to release that quite soon anyway, and there is a workaround in the meantime. In 1.2.0 we want the apache client to be the default anyway, don't we?

**Comment by wujiming** [comment]
赶上直播了吗，正好我也遇到了这个问题

**Comment by marcingrzejszczak** [comment]
I agree with @dsyer - let's put it into 1.2.0.

**Pull request closed without merging**
