### PR TITLE
Update docs to indicate the need for spring-cloud-starter-atlas

### PR DESCRIPTION
**Pull request by jkschneider**
`spring-cloud-starter-atlas` adds the Jackson Smile library necessary to properly format the post to Atlas.

### CODE REVIEW

**Comment by anthonyikeda** [comment]
Thanks for that Jon, I'll give that a run in the morning!

**Comment by jkschneider** [comment]
@anthonyikeda working on a spring-cloud-sample right now to demonstrate, I'll share with you when done

**Comment by anthonyikeda** [comment]
Let me update my gist with the gradle config and the application aspects to
show you what I have (event adding the atlas dependency I'm getting the
NullPointer, I addd smile separately originally)

**Comment by anthonyikeda** [comment]
I've added in my bootstrap.yml, build.gradle (including the newly added
spring-cloud-starter-atlas), a manager implementation showing an example of
a Timer, and the main Application enabling Atlas. I recompiled but the unit
test I have on the DepartmentManagerImpl is still throwing the same
NullPointerException. I also have aloha instance of Atlas running.

Maybe I'm doing something wrong?

**Comment by anthonyikeda** [comment]
https://gist.github.com/anthonyikeda/0f01df1045c9b231044b

**Comment by anthonyikeda** [comment]
The application log is now added also for clarity.

**Comment by anthonyikeda** [comment]
The Spock spec on the DepartmentManagerImpl fails when testing the
getDepartment(String id) method that uses the Timer.

When trying to skip tests and running the application, there seems to be a
wiring issue with the Spectator Metrics Services:

NoUniqueBeanDefinitionException: No qualifying bean of type
[org.springframework.boot.actuate.metrics.GaugeService] is defined:
expected single matching bean but found 2:
gaugeService,spectatorMetricServices

**Comment by jkschneider** [comment]
Thanks, clearly a few different things to look at.  If I remember correctly, `@AutoConfigureBefore(EndpointAutoConfiguration.class)` was supposed to pre-empt the actuator GaugeService, but perhaps there is some other ordering issue here.

**Comment by jkschneider** [comment]
I don't see the missing netflix.atlas.uri problem in my sample app, so there is something else going on here to find.

**Comment by jkschneider** [comment]
@anthonyikeda this is what I'm working off of currently: https://github.com/jkschneider/spring-cloud-atlas-sample

**Comment by anthonyikeda** [comment]
I'm going to try building off the samples project rather than apply to an
existing project to get a better understanding as I still can't get this to
work in my own project.

Anthony

**Comment by anthonyikeda** [comment]
I think I'm making progress, in my examples I'm annotating the main class
with @SpringCloudApplication, not @SpringBootApplication. Swapping that
over has so far removed any errors when running the app as bootRun - the
Unit Test still report the NullPointerException.

Mind you my Spock Specs are written in Groovy - not sure if that would be a
problem.

When Running with @SpringCloudApplication it looks like there is some
wiring of the GaugeService already performed - thus the conflict:

Error creating bean with name
'org.springframework.cloud.netflix.hystrix.HystrixCircuitBreakerConfiguration$HystrixMetricsPollerConfiguration':
Injection of autowired dependencies failed; nested exception is
org.springframework.beans.factory.BeanCreationException: Could not autowire
field: private org.springframework.boot.actuate.metrics.GaugeService
org.springframework.cloud.netflix.hystrix.HystrixCircuitBreakerConfiguration$HystrixMetricsPollerConfiguration.gauges;
nested exception is
org.springframework.beans.factory.NoUniqueBeanDefinitionException: No
qualifying bean of type
[org.springframework.boot.actuate.metrics.GaugeService] is defined:
expected single matching bean but found 2:
gaugeService,spectatorMetricServices


Do you want me to create a new defect ticket?

Anthony

**Comment by anthonyikeda** [comment]
Yup, @SpringCloudApplication adds in the @EnableHystrix annotation as part
of it's declaration. If I use @SpringBootApplication and @EnableHystrix I
get the same error.

**Comment by jkschneider** [comment]
@anthonyikeda thanks for hunting down the reason -- fix is in #735

**Pull request merged**
