### PR TITLE
Update SimpleHostRoutingFilter.java

### PR DESCRIPTION
**Pull request by shanman190**
Check if request Content-Type header is null before creating a ContentType object.

Fixes gh-1037

### CODE REVIEW

**Comment by spencergibb** [comment]
how about a test case?

**Comment by spencergibb** [comment]
Have you signed the [Contributor License Agreement](https://support.springsource.com/spring_committer_signup)?

**Comment by shanman190** [comment]
Yeah, I can write up a quick test case for it. I've signed one of the CLAs before, I think it was in relation to Spring Boot, but I can do it again if need be.

**Comment by spencergibb** [comment]
Nope, once is enough.

**Comment by shanman190** [comment]
Alright, so looking closer at this change I'm beginning to wonder how valuable such a test would be as I'd have to be getting into the internals of the class just to cause the reported behaviour. (eg Reflection to overlay the http client that's hidden within the class itself and building up almost all of an HTTP Request) Unless you guys have some other suggestions for testing this guy I'm not sure how much I can manage here...

**Comment by spencergibb** [comment]
I'm unsure why you would use reflection for the test case. We do many tests where we send real requests to zuul.

**Comment by shanman190** [comment]
Yeah. I was trying to write the wrong kind of test. I was thinking a unit test rather than an integration test. I think that I can create a test that causes the behavior described in the issue. But it will take me some time to do that. The error is a combination of the addition of the header with the string value of null in combination with using an OAuth protected resource and having an expired OAuth token. Both services are running Zuul in my case. The first one is running a UI application and the second one is an API application proxying downstream services. The UI application adds the Content-Type header with an invalid value from the perspective of the MediaType class. The DefaultOAuth2ExceptionRenderer class makes a call to the getHeaders method of the ServletServerHttpRequest class which then tries to get the Content-Type cascading eventually down to where the exception is being thrown.

**Comment by shanman190** [comment]
Alright. I've gotten two test cases written around the error. The first is a successful request, get an OAuth token then call the protected endpoint, and the second is the failure test, send an invalid OAuth token and make sure that a 401 is returned instead of a 500.

**Comment by shanman190** [comment]
It appears that @dsyer fixed the issue and with a much simpler test case, so I'm not sure if this PR is still beneficial anymore. His solution is probably better because it avoids the need for bringing spring security into the test context.

**Pull request closed without merging**
