### PR TITLE
SpringMvcContract does not support path parameters defined in interface's @RequestMapping

### PR DESCRIPTION
**Pull request by jebeaudet**
Proposed fix for #1023.

I've signed the contributor's agreement. Thanks!

### CODE REVIEW

**Comment by dsyer** [comment]
I had to revert this because there were test failures. If you can rebase and fix them, that would be great.

**Comment by spencergibb** [comment]
My fear (see https://github.com/spring-cloud/spring-cloud-netflix/issues/1023#issuecomment-218629178) is that this is just not compatible with spring cloud netflix. I just haven't had time to look.

**Comment by jebeaudet** [comment]
I'll take a look at it, sorry about that, I was sure I ran the tests.

**Comment by jebeaudet** [comment]
Hmm, `mvn clean install` completes succesfully with maven 3.3.9 and openjdk 1.8_91 on ubuntu 14.04 LTS. Same with `./mvnw clean install`. Do you have any input on this? I see that the travis build fails with an OOM error so I'm not sure where to look.
Thanks

**Comment by dsyer** [comment]
Hmm. I was getting test failures in ribbon bits.

Travis is failing because of some weird javadoc thing. I would ignore it for now.

**Comment by jebeaudet** [comment]
Well, I had to disable the `Build Automatically` in eclipse while building but that's pretty much it.

**Comment by jebeaudet** [comment]
Did you have the chance to take a second look at it? Thx :+1:

**Comment by spencergibb** [comment]
Wondering if you can rework the tests to leave the `_Simple` tests as they are and add a new set with `@RequestMapping` on the interface. That way we know you haven't broken existing functionality.

**Comment by jebeaudet** [comment]
Definitely, that's a good suggestion. I'll work on that next week.

**Comment by jebeaudet** [comment]
PR updated. Do you prefer squashed commits or you'd rather do it on your end? Thx again

**Comment by dsyer** [comment]
So @spencergibb, you're not worried about compatibility any more?

@jebeaudet if you squash them it will save us time. They get squashed anyway usually, but most people don't seem to know how.

**Comment by jebeaudet** [comment]
Squashed.

**Comment by spencergibb** [comment]
@dsyer yes I am, see #1079

**Comment by jebeaudet** [comment]
OK I see, does extending the interface for your client as mentioned in http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-inheritance would help?

**Comment by spencergibb** [comment]
I don't think so. Spring MVC automatically creates controllers if a bean has `@RequestMapping` at the class level.

**Comment by jebeaudet** [comment]
I'll give it a shot with @FeignClient, as I said in the issue, we're not using it. Thanks for the hint, it might not be possible after all.

**Comment by jebeaudet** [comment]
I may be missing something but I've made a sample in https://github.com/jebeaudet/feign-client-sample reproducing exactly the pattern defined in http://cloud.spring.io/spring-cloud-static/spring-cloud.html#spring-cloud-feign-inheritance with a class level `@RequestMapping` with a path parameters. The only thing I've added is that the resource implementing the api also needs the `@PathVariable` annotations.

The repo should be self contained, I've used the Brixton release and I've created the `SpringMvcContract` class with the code from this PR in the same package as the dependency so my class has precedence.

To test, spawn the eureka server, run `UsersClientApplication` and `UsersResourceApplication`. The resource expose an endpoint on `http://localhost:8081/organizations/{organizationId}/users/{username}` which simply prints out the path parameters. The client expose an endpoint on `http://localhost:8080/` that simply proxy the resource endpoint with the path parameters `hello` and `from feign client proxy`.

I tried reproducing the issue mentioned in the link you gave @spencergibb without success, even when using `@RequestMapping` over `@FeignClient` (though I don't see why someone would do that), it didn't work but it didn't throw. I've tried with both my modified `SpringMvcContract` and the current one. 

Thanks again!

**Comment by dsyer** [comment]
I think the problem @spencergibb was worried about occurred when people put `@RestController` on their feign interfaces (which is clearly wrong but some people want us to support it). I think a `@RequestMapping` at the class level is fine. Isn't that what this PR is partly about?

**Comment by jebeaudet** [comment]
Yes, this PR is about supporting `@PathVariable` defined in the class' `@RequestMapping` (I just noticed that I've used query string all along when I meant path parameters, I'll update the commit message to be clearer).

I'm struggling to reproduce the problem mentioned in the linked issue. Also, since `@RequestMapping` is already supported at the interface level to prepend a constant path, I don't see how this PR breaks anything (see my explanation in the first comment of #1023), it just needs to be in the `MethodMetadata` before the `parseAndValidateMetadata` is called.

I'd be happy to dig around a little more but I'm not sure where to look next.

**Comment by dsyer** [comment]
I think we can probably merge this as long as the tests are fine again. Spencer can weigh in when he gets a chance.

**Comment by spencergibb** [comment]
This is what we've had problems with before https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.java#L169-L172

If you share an interface annotated with a top level `@RequestMapping` between feign and a real `@Controller` in the same project, spring will try and create a controller out of it even if it is not annotated with `@Controller`.

**Comment by jebeaudet** [comment]
OK so the client and the resource have to be in the same project which doesn't make any sense to me, why would you use a client to access a resource in the same application? Even if you have multiple application instances, it's most likely always better to directly use the service than to go through an http request...

I just want to point out that : 
- class level `@RequestMapping` is already supported in `SpringMvcContract`, only the path params defined in it are not, are we planning in deprecating the support for it?
- Separating the interface+client+resource in different projects with correct dependency management (as shown in my example) works fine.

I don't really mind if we drop this PR, we already use our custom `SpringMvcContract` to build our feign clients. It's not blocking for us but I think this improvement, if the class level `@RequestMapping` is to be still supported in future releases, should make its way into the codebase to support path params.

Once again, thanks for your inputs :+1:

**Comment by spencergibb** [comment]
I agree it doesn't make sense :-). I think this is ok to go.

**Comment by jebeaudet** [comment]
Great news, happy to contribute!

**Comment by spencergibb** [comment]
Closed with a little polish (formatting) via b3ef770819e121dfbbbda371b3e7fe6ecf587b96

**Pull request closed without merging**
