### PR TITLE
gh-892 fix zuul POST retry

### PR DESCRIPTION
**Pull request by doernbrackandre**

### CODE REVIEW

**Comment by doernbrackandre** [comment]
I tried to implement the ResettableServletInputStreamWrapper into the FormBodyWrapperFilter and faced some issues so I've moved it to an own filter. Maybe it is still possible to merge both filters..

**Comment by doernbrackandre** [comment]
@ryanjbaxter sure. I've simplified the fix to one change in the RibbonCommandContext like mentioned above. 

Gimme a moment to revert all changes and re-implement the fix :)

**Comment by doernbrackandre** [comment]
@ryanjbaxter the ContextAwareRequest depends on the RibbonCommandContext which is part of the zuul.filter.route package. Is there a reason why the context is not moved to a more generic package so that the context aware http clients no not depend on zuul?

**Comment by doernbrackandre** [comment]
@ryanjbaxter sorry. my IDE did strange thinks. I really hope you will get through this

**Comment by ryanjbaxter** [comment]
@doernbrackandre np, i understand.  If you can fix the formatting we will be happy to take a look at it.

**Pull request closed without merging**
