### PR TITLE
Rest template metrics collection fixes

### LINKED ISSUE #636: RestTemplateUrlTemplateCapturingAspect should only be applied if AspectJ is available
RestTemplateUrlTemplateCapturingAspect should only be applied if AspectJ is available. Or maybe aspectj should be a mandatory dependency? Either way there are test failures in https://github.com/spring-cloud-samples/tests.

### PR DESCRIPTION
**Pull request by jkschneider**
Conditionalize rest template metrics collection on presence of CglibAutoProxy:

* If the application has `@EnableAspectJAutoProxy(proxyTargetClass = true)`, collection is safe
* A tacit assumption of `@EnableAspectJAutoProxy` is that a direct dependency on **aspectjweaver** is also present

Fixes #636

The around advice applied by the rest template metrics collection aspect was also not returning the value of the advised method.  This has been fixed and the test updated.

### CODE REVIEW

**Comment by spencergibb** [comment]
@jkschneider @dsyer  does 36e4c7cf9307720dfca3758e796ee7521cab5d67 change the need to rely on `CglibAutoProxy`

**Comment by dsyer** [comment]
I think we can still make changes here, but the change in 36e4c7c means that a) native proxies will work if necessary, but b) all beans of type `RestTemplate` will have that concrete type at runtime if user sets `spring.aop.proxy-target-class=true`.

**Comment by spencergibb** [comment]
There's a merge conflict. Do I still need to include `@ConditionalOnBean(AopAutoConfiguration.CglibAutoProxyConfiguration.class)`?

**Comment by jkschneider** [comment]
@spencergibb @dsyer's solution is better.  It is not needed

**Comment by jkschneider** [comment]
@spencergibb No need to try to merge this necessarily, but we do need the change in 6e9045d, because currently the around advice causes `RestTemplate` to always return null!

**Comment by spencergibb** [comment]
NP, I'll get it.

**Comment by spencergibb** [comment]
Squashed and merged via 713e6b84615aa4f271f797f30289dafe1db00083

**Pull request closed without merging**
