### PR TITLE
Handle special characters in TraceProxyRequestHelper

### PR DESCRIPTION
**Pull request by Qerny**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Qerny Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3984)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3984) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Qerny Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=3984)!

**Comment by Qerny** [comment]
Do you still support version 2.1.4? Can i create pull request for this branch, or do I need to use more recent branches?

**Comment by Qerny** [comment]
@spencergibb Can you help me, please?

**Comment by OlgaMaciaszek** [comment]
We support `2.2.x` and `main`. Closing in favour of gh-3995.

**Pull request closed without merging**
