### PR TITLE
Specified minimum JDK version as 1.8

### PR DESCRIPTION
**Pull request by heyjustin**
Module spring-cloud-netflix-turbine-amqp requires JDK 1.8

### CODE REVIEW

**Comment by heyjustin** [comment]
Individual Contributor Agreement: 124720150605045930

**Comment by spencergibb** [comment]
The first line of the file says "Do not edit this file (e.g. go instead to src/main/asciidoc)".  It had already been fixed, but needed to be regenerated. Fixed via ce96c83401dc0e905cf3a8ff3c4f5ee4d253b297

**Comment by kavinduraisamy91** [comment]
@spencergibb  We are trying to build cloud netflix with JDK 1.7 and Tomcat 7(Servlet 3.0). Could you please let us know the suitable Cloud netflix version?
Note : we are using RibbonRoutingFilter. 

Currently we are facing a deployment issue in our production. It will be great if you provide the solution asap.

Thank you!

**Comment by ryanjbaxter** [comment]
@kavinduraisamy91 Please open a separate issue if you are having a problem

**Comment by vasandharaj** [comment]
@ryanjbaxter 

to add it the @kavinduraisamy91 question, i have found that the RibbonRoutingFilter.java, FormBodyWrapperFilter.java etc. are using the getContentLengthLong () from servlet 3.1 API. 

is it possible to make spring cloud dependencies backward compatible Servet API 3.0 since we are using Tomcat 7.0.65 in Production. Because of this issue it breaks.

**Comment by spencergibb** [comment]
Like @ryanjbaxter said, please open another issue.

**Pull request closed without merging**
