### PR TITLE
Add missing metadataMap property in doc example

### PR DESCRIPTION
**Pull request by ryanjbaxter**
The example was missing the metadaMap property.

### CODE REVIEW

**Comment by spencergibb** [comment]
Actually, this has changed with upgrades to eureka that I worked on with Netflix. metadataMap still works for backwards compatibility.

**Comment by ryanjbaxter** [comment]
I was using 1.2.5 and it did not seem to working, I have not ta newer version yet.  Do you think the change in 1.2.5?

**Comment by spencergibb** [comment]
Right, it is still valid for 1.2.5

**Comment by ryanjbaxter** [comment]
Hmmm it doesnt seem to be working for me, here is my eureka config

```
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.ocr-eureka.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    nonSecurePort: 80
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
```
Am I missing something?  I tried with Brixton and Angel

**Comment by spencergibb** [comment]
So metadataMap should still be used for but master.

**Comment by ryanjbaxter** [comment]
Even with using the latest Brixton snapshot build it does not seem to work....I am not sure how old the latest snapshot is but I would think it is pretty recent right?

**Comment by spencergibb** [comment]
Hmm, I tried it and it seems to be working for me: `eureka.instance.instanceId=customer2`.

**Comment by spencergibb** [comment]
image

**Comment by ryanjbaxter** [comment]
Still not working for me, here is the source code to the client app
https://dl.dropboxusercontent.com/u/58852600/demo%203.zip

I am probably doing something dumb here....

**Comment by spencergibb** [comment]
your app doesn't do it, mine does. Wonder what the difference is?

**Comment by spencergibb** [comment]
nevermind, now yours is working :-(

**Comment by spencergibb** [comment]
with Brixton.BUILD-SNAPSHOT

**Comment by ryanjbaxter** [comment]
Can you share your Eureka server and client so I can try it on my machine?

**Comment by spencergibb** [comment]
I'm using our samples: 

- https://github.com/spring-cloud-samples/configserver
- https://github.com/spring-cloud-samples/eureka
- https://github.com/spring-cloud-samples/customers-stores (just the customers service)

**Comment by ryanjbaxter** [comment]
Are there some changes in the Eureka server needed to make this work?  I noticed that once I moved my Eureka server up to the Brixton Snapshot it started working?

**Comment by spencergibb** [comment]
Yes, that's the case now that I think about it.

**Comment by spencergibb** [comment]
So maybe, the best thing to do is to mention if either component is using 1.0.x it will need to use metadataMap.

**Comment by ryanjbaxter** [comment]
I did another test and this only works with the latest Brixton Snapshot builds.  Looks like the documentation isn't versioned (there isn't a separate copy for the different builds). Right?  If that is the case than I guess we will have to clarify in the documentation which versions supports this property.

**Comment by ryanjbaxter** [comment]
@spencergibb what do you think?

**Comment by spencergibb** [comment]
We need to clarify the docs on master. The [Angel docs](http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html) still have the right stuff.

**Comment by spencergibb** [comment]
Do you want to update this PR or shall I have a shot at it?

**Comment by ryanjbaxter** [comment]
Oh somehow I clicked on the wrong link to get to the Angel docs because I thought both the Angel and Brixton docs linked to the same place.  (Or was that just updated....)  Anyways I think if the docs are correct for the right versions than there is no need to update the Brixton docs since it works there.  Unless we want to update the Brixton docs to say that in M1 you need to include the metadataMap property.

**Comment by spencergibb** [comment]
Closing in favor of the outcome of #642

**Pull request closed without merging**
