### PR TITLE
Adding the ability to specify a custom retry handler in the ribbon cl…

### PR DESCRIPTION
**Pull request by tkvangorder**
…ient configuration.

### CODE REVIEW

**Comment by spencergibb** [comment]
:+1: I'll take a look. Like I said, I need guidance on if this has to wait for SR1.

**Comment by dsyer** [comment]
LGTM (it's a small enough change we can add it in RC2 I think).

**Comment by tkvangorder** [comment]
asdflklj. I fixed the unit test failure.

**Comment by spencergibb** [comment]
Squashed and merged with a little polish via bdc5b915e83b622fbf2d316de2e8e2e1cf5b972e

**Pull request closed without merging**
