### PR TITLE
[hystrix-dashboard] use relative urls for assets

### PR DESCRIPTION
**Pull request by texdc**
In our environment, host names and url paths are not known until deploy time.  Setting `server.contextPath` manually is not accurate:

```yml
# application.yml
server:
  contextPath: /foo
```
puts things in `{host}/foo/foo/hystrix` instead of `{host}/foo/hystrix`.

Simply using relative paths eliminates any context work-arounds.  I've also refactored a lot of the javascript to reduce redundancy and improve efficiency.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@texdc Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2127)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2127) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@texdc Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=2127)!

**Comment by texdc** [comment]
The formatting is kept separate.  Walking through the commits sequentially makes it easier to review.

**Comment by spencergibb** [comment]
I'm asking you to remove the formatting changes

**Comment by texdc** [comment]
The formatting makes it easier to read, comprehend, and maintain.  If there is a bug or other oversight, please let me know and I'll be happy to address it.

**Comment by spencergibb** [comment]
Let me know when you've removed the formatting. We squash pull requests so they appear as one commit. I'm happy to review a separate PR with formatting changes.

**Comment by jdhom** [comment]
Hi @spencergibb, are you talking just about whitespace/alignment or reorganizing some code (like the javascript includes)?

**Comment by spencergibb** [comment]
All formatting that doesn't have significant impact on functionality.

**Comment by spencergibb** [comment]
Even with those changes removed, it's a lot beyond the scope of just using relative paths. I'm actually questioning the reason behind this. We have tests to verify things still work when the context-path is set.

https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-hystrix-dashboard/src/test/java/org/springframework/cloud/netflix/hystrix/dashboard/HystrixDashboardContextTests.java#L42

**Comment by texdc** [comment]
It's the Boy Scout Rule.  As mentioned in the description: setting the context-path is not effective in our environment.  Relative urls are simple and work regardless of context settings.

**Comment by spencergibb** [comment]
> It's the Boy Scout Rule.
I don't know what that means.

I'd like to know why context-path doesn't work in your environment.

**Comment by spencergibb** [comment]
This module has entered [maintenance mode](https://github.com/spring-cloud/spring-cloud-netflix#modules-in-maintenance-mode). This means that the Spring Cloud team will no longer be adding new features to the module. We will fix blocker bugs and security issues, and we will also consider and review small pull requests from the community.

**Pull request closed without merging**
