### PR TITLE
Migrate tests to Spring Boot Test 1.4

### LINKED ISSUE #1205: Migrate tests to Spring Boot Test 1.4
Since the Spring Boot 1.4 upgrade, all the tests are now using deprecated API such as `@WebIntegrationTest` and `@SpringApplicationConfiguration`.

All the tests should be migrated to `SpringBootTest`.

See blog entry from Philip [here](https://spring.io/blog/2016/04/15/testing-improvements-in-spring-boot-1-4).

### PR DESCRIPTION
**Pull request by daniellavoie**
Fixes #1205.

### CODE REVIEW

**Comment by daniellavoie** [comment]
That is a big one. Mostly, `@IntegrationTest`, `@SpringApplicationConfiguration ` and `@WebIntegrationTest` were replace by `@SpringBootTest`. Some classes were reformated with Eclipse Spring Cloud Formatter.

**Comment by daniellavoie** [comment]
@ryanjbaxter @dsyer 

Hello guys, any bandwitch for this PR on 1.2.0.M1 or M2 ?

**Comment by spencergibb** [comment]
We're all at Spring One or on PTO this week.

**Comment by daniellavoie** [comment]
Of course :) hope I'll be there next year.

**Comment by ryanjbaxter** [comment]
Thanks!

**Pull request merged**
