### PR TITLE
Disable cookie management for RibbonLoadBalancingHttpClient Fixes gh-301

### PR DESCRIPTION
**Pull request by denyska**

### CODE REVIEW

**Comment by spencergibb** [comment]
ping @ryanjbaxter

**Comment by ryanjbaxter** [comment]
Should this be included in 1.1.x as well?

**Comment by ryanjbaxter** [comment]
@denyska ^^^ would you like to see this in the Brixton release as well?

**Comment by denyska** [comment]
@ryanjbaxter it will be nice to see it in Brixton too. At least I will be able to undo my ugly workaround.

**Comment by ryanjbaxter** [comment]
@denyska would you mind creating a pull request against the 1.1.x stream for this as well?  It is not as strait forward to apply these changes to that branch since some of the tests are different.

**Pull request merged**
