### PR TITLE
Set or append to X-Forwarder-For header on Zuul requests

### LINKED ISSUE #352: Zuul and X-Forwarded-For
Should Zuul support X-Forwarded-For out of the box? Just like it sets X-Forwarded-Host

### PR DESCRIPTION
**Pull request by timtebeek**
Fixes #352

### CODE REVIEW

**Comment by dsyer** [comment]
Is it worth maybe checking for duplicates (no need to add an address that is already there because of an upstream proxy)?

**Comment by timtebeek** [comment]
Good point, updated accordingly.. Anything else I might add? I saw I'm slightly off-standard with my lack of curly brackets.. That is easily fixed if needed.

**Comment by dsyer** [comment]
I think the braces are covered by a checkstyle rule, but the easiest way to fix them is to use Eclipse and load the coding conventions from the source (https://github.com/spring-cloud/spring-cloud-netflix/tree/master/eclipse).

**Comment by timtebeek** [comment]
Just saw https://github.com/spring-cloud/spring-cloud-netflix/commit/593549551ac93848328203e1ad5bba8a60c20cd3 ; Great! Does that mean I can close this pull request? Or what's the proper flow?

**Comment by spencergibb** [comment]
Closed via 593549551ac93848328203e1ad5bba8a60c20cd3

**Pull request closed without merging**
