### PR TITLE
Update CloudEurekaClient.java

### PR DESCRIPTION
**Pull request by Wangxiaoman**
update log class

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Wangxiaoman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1548)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-netflix&pullRequestId=1548) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by ryanjbaxter** [comment]
@Wangxiaoman please sign the CLA so we can commit this change

**Comment by spencergibb** [comment]
ping @Wangxiaoman

**Comment by spencergibb** [comment]
Superceded by 652fe97a1b645f1338451aa47299ed2f362a3a94

**Pull request closed without merging**
