### PR TITLE
Support slice testing of zuul components

### PR DESCRIPTION
**Pull request by bijukunjummen**
Supports #2419 - Slice testing of Zuul filter and properties. If this looks good I can send another PR to update the documentation.

### CODE REVIEW

**Comment by bijukunjummen** [comment]
Note that Discovery based Ribbon `ServerList` is disabled for the slice test, this way there is no dependency on needing any registry for these slice tests and the target zuul endpoint needs to be explicitly specified for tests using `listOfServers` - `serviceId.ribbon.listOfServers=localhost:${wiremock.server.port}`. If we absolutely need to support Discovery for Ribbon an option could be to hook up `SimpleDiscoveryClient` based `ServerList` and use it instead(such an auto-configuration does not exist but can be added if desired)

**Comment by ryanjbaxter** [comment]
Is there some kind advantage to doing it this way as opposed to using spring cloud contract?

**Comment by bijukunjummen** [comment]
Yes, good point @ryanjbaxter.  S-C-Contract  would assume that we have contract's defined for all downstream services that Zuul is fronting, which likely may not be available + typically since Zuul is used for hiding legacy services typically those may be say SOAP based services. 

The approach in the PR is to leave it to the user during test to define a stub behavior for the downstream service (using `@AutoConfigureWireMock`) and then test purely using MockMvc

**Comment by ryanjbaxter** [comment]
OK maybe I misunderstood the use case.  This is not for testing our Zuul implementation in SC Netflix its for testing apps using Zuul, right?

**Comment by bijukunjummen** [comment]
Yes, that is correct @ryanjbaxter - I faced an issue at a customer location where we added Zuul proxy to an existing application and this application uses some shared libraries with its own set of auto-configurations. Now to test the Zuul specific configuration we could exclude all the auto-configurations that the customer has OR test it by activating only Zuul specific auto-configurations. 

These specific auto-configurations which worked for at the customer location are now part of this slice test

**Comment by ryanjbaxter** [comment]
Makes sense, could we get some documentation then on how its used?

**Comment by bijukunjummen** [comment]
Oh yes, sounds good @ryanjbaxter, will update the PR with documentation on how to use this

**Comment by bijukunjummen** [comment]
Added in documentation now @ryanjbaxter

**Pull request closed without merging**
