### PR TITLE
Fix incorrect default values in docs (#4294)

### PR DESCRIPTION
**Pull request by 555cider**

### CODE REVIEW

**Comment by spencergibb** [comment]
That file is auto generated, so editing it directly is not the right way to do this

**Comment by OlgaMaciaszek** [comment]
Right. @555cider what seems to happen is that the default values in `@ConfigurationProperties` classes defining those props (for example, `EurekaClientConfigBean`, `EurekaServerConfigBean`), are not explicitly specified, but using math equations with constants instead, for instance: https://github.com/spring-cloud/spring-cloud-netflix/blob/57dd4f06744dba5af4fe4ac8dfb971665fd73f30/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientConfigBean.java#L99, so what you'd need to do is instead of changing that `configprops` file, change the default values in those `@ConfigurationProperties` classes to explicit values (you could add comments such as "5 * MINUTES" where helpful.

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks @555cider, please adjust the changes as described here: https://github.com/spring-cloud/spring-cloud-netflix/pull/4321#issuecomment-2374741265

**Review by OlgaMaciaszek — CHANGES_REQUESTED** [review]
Thanks, @555cider - the changes look good; have you regenerated the configprops file with the new changes (in order to do that, remove any manual changes in the file and run `./mvnw clean install -Pdocs` locally and the file will be regenerated)? Also, please add your full name and surname with `@author` tag in the javadocs of the classes you've modified and update the dates in the years in the license comment on top of the class to  `-2024`. Finally, could you submit your changes against the `4.1.x` branch instead of `main`?

**Comment by 555cider** [comment]
I have applied all the changes you requested except for the regeneration of the configprops file. I was unable to regenerate the file because it involves removing any manual changes and running `./mvnw clean install -Pdocs` locally.

Just in case, I've reverted the _configprops file back to its original state.

Also, I accidentally merged the main branch while clicking around the site. I force pushed to clean up the git history, but if this action is not allowed, I will create a new pull request. In that case, I will modify the branch based on the "4.1.x" branch and submit the request.

**Comment by OlgaMaciaszek** [comment]
Thanks @555cider - waiting for the new PR.

**Comment by 555cider** [comment]
Creating a new pull request (#4999) and closing this pull request (#4321).

**Pull request closed without merging**
