### PR TITLE
Prevent RibbonRoutingFilter throws exceptions when Http status codes are non-standard

### LINKED ISSUE #2639: Zuul: RibbonRoutingFilter throws error for non standard http status codes
We are using Spring Boot 1.5.9-RELEASE and spring-cloud-starter-zuul. One of the backend services we forward requests to provide non standard http status codes like 517. 

The current version of zuul contains a version of the RibbonRoutingFilter which executes on the ClientHttpResponse object following call: `.getStatusCode().value()` 

This causes an IllegalArgumentException. Since the filter requires the int value of the status code you could replace these calls by `.getRawStatusCode()` which do not throw an exception

### PR DESCRIPTION
**Pull request by holy12345**
This PR fixes #2639

### CODE REVIEW

**Comment by spencergibb** [comment]
Please change the title to something descriptive

**Comment by holy12345** [comment]
@spencergibb 
Thanks for your reply, I have modified the title according to your suggestion and added a test code.

**Comment by holy12345** [comment]
Hi @ryanjbaxter 
I hope you can look at this PR, where else need to be modified? If you have requested, I will promptly amend. Thanks again

**Comment by ryanjbaxter** [comment]
@holy12345 there are test failures both on circleci and when i build locally
```
Failed tests:   requestFactoryIsRibbon(org.springframework.cloud.netflix.ribbon.RibbonClientHttpRequestFactoryTests): (..)
```

**Comment by ryanjbaxter** [comment]
Also this will be useful in the 1.4.x branch

**Comment by spencergibb** [comment]
I recently fixed that test. A rebase on master will fix it.

**Comment by holy12345** [comment]
@ryanjbaxter Thank you for reviewing my code. I'm happy to get your reply.
@spencergibb Thank you for fixing this test.
In addition, I would like to ask, next I still need to do for this PR?

Thanks for all

**Comment by ryanjbaxter** [comment]
@holy12345 can you submit this agains the 1.4.x branch?

**Comment by holy12345** [comment]
@ryanjbaxter 
Thank you very much. I resubmitted a PR(#2671). The PR(#2671) against  the 1.4.x branch.(The reason I resubmitted is that I do not know how PR against the 1.4.x branch and if you can tell me I will be very grateful to you)

**Pull request closed without merging**
