### PR TITLE
Upgrade Hystrix

### PR DESCRIPTION
**Pull request by tinexw**

### CODE REVIEW

**Comment by spencergibb** [comment]
That version has never made it to maven central https://repo1.maven.org/maven2/com/netflix/hystrix/hystrix-core/

**Comment by tinexw** [comment]
Sorry about that! It was [supposedly released](https://github.com/Netflix/Hystrix/releases/tag/v1.5.13) and contains a bug fix I need. It does exist in [bintray](https://bintray.com/netflixoss/maven/Hystrix/1.5.13#). 
There is an open issue asking why it's missing in maven central:  https://github.com/Netflix/Hystrix/issues/1852

**Comment by spencergibb** [comment]
https://github.com/Netflix/Hystrix/issues/1629 is over a year old

**Comment by tinexw** [comment]
I saw :-( Do you know by any chance if anyone is actually maintaining Hystrix?

**Pull request closed without merging**
