### PR TITLE
secureHealthCheckUrl fix issue-3655

### PR DESCRIPTION
**Pull request by epm-dev-priporov**
fix  for #3655 issue

### CODE REVIEW

**Comment by epm-dev-priporov** [comment]
Also thre is a weird code in class _EurekaClientAutoConfiguration_

            instance.setNonSecurePort(serverPort);
		instance.setInstanceId(getDefaultInstanceId(env));
		instance.setPreferIpAddress(preferIpAddress);
		instance.setSecurePortEnabled(isSecurePortEnabled);
		if (StringUtils.hasText(ipAddress)) {
			instance.setIpAddress(ipAddress);
		}

		if (isSecurePortEnabled) {
			instance.setSecurePort(serverPort);
		}

serverPort  is used in _isSecurePortEnabled ==  true_ case.
Is that ok?

**Comment by spencergibb** [comment]
After a review and trying to polish I'm not sure this is all correct. What is the priority between secureport, port and management port?

**Comment by epm-dev-priporov** [comment]
I would say that each thing called securitySomething has more higher priority than just something) In this particular case it will be not obvious if security port will be overwritten y any other, but this is just my opinion

**Comment by spencergibb** [comment]
except if management port is defined, actuator is on that port. port and secure port only matter if management port isn't defined as far as the health check url is involved.

**Comment by epm-dev-priporov** [comment]
In my opinion that is not obvious behaviour. As a developer I would like to get some info about that during spring boot starting, even maybe I would expect to get an exception with some details

**Comment by spencergibb** [comment]
@epm-dev-priporov I'm unsure how to proceed. The management port has nothing to do with the secure port of the main context.

**Pull request closed without merging**
