### PR TITLE
update RequestParamParameterProcessor to support map param

### PR DESCRIPTION
**Pull request by lowzj**
see issue #1097

### CODE REVIEW

**Comment by lowzj** [comment]
travis-ci build error, since **[travis-ci job #1353](https://travis-ci.org/spring-cloud/spring-cloud-netflix/builds/137171596)**:
```
[ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /home/travis/.m2/repository/com/netflix/eureka/eureka-client/1.4.8/eureka-client-1.4.8.jar(com/netflix/discovery/DiscoveryClient.class): warning: Cannot find annotation method 'name()' in type 'Monitor': class file for com.netflix.servo.annotations.Monitor not found
...
[ERROR] Error fetching link: /home/travis/build/spring-cloud/spring-cloud-netflix/spring-cloud-netflix-eureka-client/target/apidocs/package-list. Ignored it.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-source-plugin:3.0.0:jar (attach-sources) on project spring-cloud-netflix-eureka-server: Error creating source archive: Problem creating jar: Execution exception: Java heap space -> [Help 1]
```

**Comment by spencergibb** [comment]
yeah, we had to revert a fix for travis, don't worry about that.

**Comment by spencergibb** [comment]
@lowzj any chance you could add some tests?

**Comment by lowzj** [comment]
At first I run the test I wrote in this pr, it passed. Then I recompile the whole project, and test again, it failed. I create a new spring-boot project, include the `spring-cloud-netflix-core` dependency and run the same test again, it passed. 

I debug the test and find the problem in my case, and I think probably there is something wrong in the method `SpringMvcContract#synthesizeWithMethodParameterNameAsFallbackValue`.

```
private Annotation synthesizeWithMethodParameterNameAsFallbackValue(
	Annotation parameterAnnotation, Method method, int parameterIndex) {
    ...
    String[] parameterNames = PARAMETER_NAME_DISCOVERER.getParameterNames(method);
    ...
}
```
The code above finally invokes the method `java.lang.reflect.Executable#getParameters --> privateGetParameters --> getParameters0`. 
I'm not sure about the mechanism of `java.lang.reflect.Executable#getParameters0`, I find that it doesn't always return the expected result.

```
	public interface TestTemplate_MapParams {
		@RequestMapping(value = "/test", method = RequestMethod.GET)
		ResponseEntity<TestObject> getTest(@RequestParam Map<String, String> params);
	}
```
In this case , `parameterNames` expected result is **["params"]**. 
In this project, `getParameters0` return **["params"]**, and it's according to the class file. It's the expected result.
When I start a new project using the `spring-cloud-netflix-core`, `getParameters0` return **null** then `Executable` synthesize all parameters' names(`'arg'+parameterIndex`) and return **["arg0"]**. **arg0** is not according to the class file, so `parameterNames` would be **null**. So there is no fallback value for the annotation `name/value` attributes.

I haven't resolve this problem(may be not) now, but I think that only a simple property need a fallback value , such as `String, Long, int...` and so on.

**Comment by lowzj** [comment]
Finally, I find that `java.lang.reflect.Executable#getParameters0` depends on compiler options
```
$ javac --help
...
-parameters                Generate metadata for reflection on method parameters
...
```

Then I add these code in my own project pom.xml

```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <compilerArgs>
                    <arg>-parameters</arg>
                </compilerArgs>
            </configuration>
        </plugin>
    </plugins>
</build>
```

the method `java.lang.reflect.Executable#getParameters0` return the expected result.

**Comment by lowzj** [comment]
java documents explain my problem: [Obtaining Names of Method Parameters](https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html)

**Comment by spencergibb** [comment]
So `-parameters` is java 8 functionality and, except for a module or two, we are still baselined at java 7.

**Comment by lowzj** [comment]
thanks, I got it.

**Comment by spencergibb** [comment]
@lowzj if this requires java 8 we won't be able to merge.

**Comment by lowzj** [comment]
@spencergibb it support java 7/8. I modify the `SpringMvcContract#synthesizeWithMethodParameterNameAsFallbackValue` to just affect simple properties.

**Comment by spencergibb** [comment]
Squashed and merged with a bit of polish via dc26b1efa8bf895505825c3aa09a856b65258295

**Comment by lynchlee** [comment]
👍

**Pull request closed without merging**
