### PR TITLE
Expose some private fields via protected getters to allow easier cust…

### PR DESCRIPTION
**Pull request by TheSentinel454**
…omization. Fixes gh-1598

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
Not sure I see the need for these changes, can you elaborate on the use case?

**Comment by TheSentinel454** [comment]
Basically, if I want to create a custom Route Locator, but base it off of a lot of the SimpleRouteLocator functionality, I can't do so without copying and pasting a lot of the functionality that is in the Simple Route Locator.  Instead, if we make the fields available via protected getters, we can inherit a lot of the core functionality and just customize the portion we want, such as the getMatchingRoute method.

Does that help?

**Comment by ryanjbaxter** [comment]
I can buy some of this, but some of those variables are just used in logging in `getMatchingRoute`, maybe we could add a utility method for that functionality and make that protected?

**Comment by TheSentinel454** [comment]
Yea, that makes sense. Let me try to rework this a bit.

Thanks for the feedback!

-Luke Tornquist

**Comment by TheSentinel454** [comment]
@ryanjbaxter I've updated the PR based on your suggestions.  I also did some updating of the logic to kind of clean it up, such as adding the optional return type for the getZuulRoute method.

Let me know what you think.

**Comment by spencergibb** [comment]
Master is still Java 7, please remove the optional reference

**Pull request merged**
