### PR TITLE
Fix health-check-url duplicated contextpath

### PR DESCRIPTION
**Pull request by MadeInChina**
Fixed, just remove duplicate path if necessary

```
	private String constructValidUrl(String scheme, String hostname, int port,
			String contextPath, String statusPath) {
		try {
			if (!contextPath.endsWith("/")) {
				contextPath = contextPath + "/";
			}
			String refinedContextPath = '/'
					+ StringUtils.trimLeadingCharacter(contextPath, '/');
			URL base = new URL(scheme, hostname, port, refinedContextPath);
			String refinedStatusPath = refinedStatusPath(statusPath, contextPath);
			return new URL(base, refinedStatusPath).toString();
		}
		catch (MalformedURLException e) {
			String message = getErrorMessage(scheme, hostname, port, contextPath,
					statusPath);
			throw new IllegalStateException(message, e);
		}
	}

	private String refinedStatusPath(String statusPath, String contextPath) {
		if (statusPath.startsWith(contextPath) && !"/".equals(contextPath)) {
			statusPath = StringUtils.replace(statusPath, contextPath, "");
		}
		return StringUtils.trimLeadingCharacter(statusPath, '/');
	}
```

### CODE REVIEW

**Comment by MadeInChina** [comment]
@spencergibb 
Seems there was something wrong on ci.
```

[INFO] Spring Cloud Netflix Eureka Server ................. FAILURE [ 58.649 s]
[INFO] Spring Cloud Starter Netflix Eureka Client ......... SKIPPED
[INFO] Spring Cloud Starter Netflix Eureka Server ......... SKIPPED
[INFO] Spring Cloud Netflix Docs .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:41 min
[INFO] Finished at: 2020-06-05T14:59:56Z
[INFO] Final Memory: 135M/1040M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project spring-cloud-netflix-eureka-server: Compilation failure: Compilation failure: 
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationServletPathTests.java:[22,17] package org.junit does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationServletPathTests.java:[23,24] package org.junit.runner does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/ApplicationServletPathTests.java:[43,2] cannot find symbol
[ERROR]   symbol: class RunWith
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/EurekaServerTests.java:[21,17] package org.junit does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/EurekaServerTests.java:[22,24] package org.junit.runner does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/AbstractDocumentationTests.java:[34,17] package org.junit does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/AbstractDocumentationTests.java:[35,17] package org.junit does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/AbstractDocumentationTests.java:[36,24] package org.junit.runner does not exist
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/AbstractDocumentationTests.java:[63,2] cannot find symbol
[ERROR]   symbol: class RunWith
[ERROR] /home/appuser/project/spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/doc/EurekaServerTests.java:[30,2] cannot find symbol
[ERROR]   symbol: class RunWith
```

**Comment by spencergibb** [comment]
It was a change in boot that we need to adapt to.

**Comment by MadeInChina** [comment]
@spencergibb Please check.
All good now.

**Comment by MadeInChina** [comment]
@spencergibb Could you please help me to merge it?

**Pull request closed without merging**
