### PR TITLE
% preserve upstream character encoding

### PR DESCRIPTION
**Pull request by paiv**
see #530

### CODE REVIEW

**Comment by spencergibb** [comment]
Have you signed the [contributor's agreement](https://support.springsource.com/spring_committer_signup)? Also, how about a test that proves what you did fixes the issue?

**Comment by spencergibb** [comment]
@paiv waiting for your ack that you signed.

**Comment by paiv** [comment]
sorry, not signing atm. If this blocks you, you can close this PR.

**Comment by spencergibb** [comment]
Closing, won't sign contributors agreement.

**Pull request closed without merging**
