### PR TITLE
Set proper status and health eureka urls if prefer ip address is set

### PR DESCRIPTION
**Pull request by Aloren**

### CODE REVIEW

**Comment by Aloren** [comment]
@ryanjbaxter please check. Thanks!

**Comment by ryanjbaxter** [comment]
@Aloren should we not be checking the `prefer-ip-address` property?

**Comment by Aloren** [comment]
It's already checked in `EurekaInstanceConfigBean`:
```
	public String getHostName(boolean refresh) {
		if (refresh && !this.hostInfo.override) {
			this.ipAddress = this.hostInfo.getIpAddress();
			this.hostname = this.hostInfo.getHostname();
		}
		return this.preferIpAddress ? this.ipAddress : this.hostname;
	}
```

**Comment by ryanjbaxter** [comment]
OK.  The code also exists in the 1.4.x stream right?  Can you submit the PR against that branch and then we can merge it forward?

**Comment by Aloren** [comment]
I will submit another pull request to 1.4.x, since codebase in `EurekaClientAutoConfiguration` differs between master and 1.4.x. OK?

**Comment by ryanjbaxter** [comment]
We can close this PR since we can just merge the other PR forward

**Pull request closed without merging**
